homeassistant:
  name: Home
  latitude: !secret lat_num
  longitude: !secret long_num
  elevation: 315
  unit_system: metric
  time_zone: America/Toronto
  customize: !include_dir_merge_named customize/
  
panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

automation: !include_dir_merge_list automation/

binary_sensor: !include binary_sensor.yaml

camera:
  platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=XLA&brand=wui&num=1&delay=15&type=C0R&frame=0&scale=1.000&noclutter=0&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=0&rand=25277952&lat=0&lon=0&label=you
  name: YVO
  
amcrest:
  - host: 192.168.67.103
    username: admin
    password: !secret cam1_pass
    name: Back Yard Cam
#    resolution: high
#    stream_source: snapshot
    sensors:
      - motion_detector
  
  - host: 192.168.67.112
    username: admin
    password: !secret cam2_pass
    name: Parking Cam
#    resolution: high
#    stream_source: snapshot
    sensors:
      - motion_detector

#  - host: 192.168.67.114
#    username: admin
#    password: !secret cam3_pass
#    authentication: basic
#    name: Side Cam
#    resolution: high
#    stream_source: snapshot
#    sensors:
#      - motion_detector
        

device_tracker: !include device_tracker.yaml

# Groups
group: !include_dir_merge_named group
input_boolean: !include input_boolean.yaml
input_select: !include_dir_merge_named input_select
script: !include_dir_merge_named script
rest_command: !include_dir_merge_named rest_command
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch

remote:
  - platform: harmony
    name: LivingRoom
    host: 192.168.67.107

#light: !include light.yaml

notify:
  - name: NOTIFIER_NAME
    platform: nma
    api_key: !secret nma

logbook: #!include logbook.yaml

#logger: !include logger.yaml

recorder:
  db_url: !secret db_url

#scene: !include scene.yaml

#weblink: !include weblink.yaml

#zone: !include zone.yaml  

# Show links to resources in log and frontend
#introduction:

##################################################################################
##                                  Platforms                                   ##
##################################################################################

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.5/site-packages/python_openzwave/ozw_config

hue:
  bridges:
    - host: 192.168.67.106

##################################################################################
##                                    Options                                   ##
##################################################################################

# Enables the frontend
frontend:

# Configures frontend options
http:
#  base_url: !secret http_url
  api_password: !secret http_password
#  ssl_certificate: !secret http_ssl_certificate
#  ssl_key: !secret http_ssl_key

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Include Config panel in front end
config:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor

# Text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_api_key
    aws_secret_access_key: !secret aws_access_key
    region_name: 'us-east-2'
    text_type: ssml
    voice: Joanna
    cache: True

# Track the sun
sun:

media_player:
  - platform: vlc
    name: speaker_1
    arguments: '--aout alsa --alsa-audio-device=hw:0,0'
  - platform: vlc
    name: speaker_2
    arguments: '--alsa-audio-device=hw:0,0'

