##################################################################################
##                               Custom switch                                        ##
##################################################################################

#tv custom commands
- platform: command_line
  switches:
    livingroomtvstbdenon:
      command_on: "/home/homeassistant/.homeassistant/on.sh"
      command_off: "/home/homeassistant/.homeassistant/off.sh"

#stop camera start camera
- platform: command_line
  switches:
    camera_stop_start:
      command_on: "sudo /etc/init.d/displaycameras start"
      command_off: "sudo /etc/init.d/displaycameras stop"
  
- platform: template
  switches:
    scanner:
      friendly_name: scanner
      value_template: "{{ is_state('media_player.speaker_1', 'on') }}"
      turn_on:
        service: media_player.play_media
        entity_id: media_player.speaker_1
        data:
          media_content_id: "http://192.168.67.111:8082"
          media_content_type: "audio/mp3"
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.speaker_1
