##################################################################################
##                               Sensors                                        ##
##################################################################################

##################################################################################
##                               ZWave Sensors                                  ##
##################################################################################
# ZWave Aeotec sensors
- platform: template
  sensors:
    bedroom_door_status:
      value_template: '{% if states.binary_sensor.aeotec_zw112_door_window_sensor_6_sensor.state %}
        {% if states.binary_sensor.aeotec_zw112_door_window_sensor_6_sensor.state == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Bedroom Door'
    basement_window_status:
      value_template: '{% if states.binary_sensor.aeotec_zw112_door_window_sensor_6_sensor_2.state %}
        {% if states.binary_sensor.aeotec_zw112_door_window_sensor_6_sensor_2.state == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Basement Window'

##################################################################################
##                               Weather sensors                               ##
##################################################################################        
  
# yr sensor  
- platform: yr
  
# Wunderground sensors  
- platform: wunderground
  api_key: 63ce87d23a0d7f1f
  monitored_conditions:
    - alerts
    - feelslike_c
    - heat_index_c
    - temp_c
    - precip_today_string
    - precip_1d_mm
    - precip_1d
    - visibility_km
    - wind_dir
    - wind_kph
    - wind_1d_kph

##################################################################################
##                               Energy Sensors                                 ##
##################################################################################

# Hydroquebec API sensor      
- platform: hydroquebec
  username: unbornx
  password: !secret hydro_pass
  contract: !secret hydro_contract
  monitored_variables:
   - yesterday_total_consumption
   - yesterday_average_temperature
   - period_total_consumption
     
##################################################################################
##                               Batterysensors                                 ##
##################################################################################     
  
# Multi sensor entrance, zwave door and window sensor
- platform: template
  sensors:
    bat_fibaro:
      friendly_name: 'Fibaro sensor Battery'
      value_template: '{{ states.zwave.fibaro_system_fgms001zw5_motion_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'
    bat_patio_sensor:
      friendly_name: 'Patio sensor Battery'
      value_template: '{{ states.zwave.aeotec_zw112_door_window_sensor_6.attributes.battery_level }}'
      unit_of_measurement: '%'
    bat_basement_window_sensor:
      friendly_name: 'Basement window sensor Battery'
      value_template: '{{ states.zwave.aeotec_zw112_door_window_sensor_6_2.attributes.battery_level }}'
      unit_of_measurement: '%'
        
##################################################################################
##                               System monitoring sensor                       ##
##################################################################################
- platform: rest
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

- platform: rest
  resource: http://api.zap2it.com/tvlistings/webservices/whatson?stnlt=58592
  name: zap
  value_template: '{{ value_json.results.schedules[0].title }}'
- platform: rest
  resource: http://api.zap2it.com/tvlistings/webservices/whatson?stnlt=73275
  name: zaprds2
  value_template: '{{ value_json.results.schedules[0].title }}'
- platform: rest
  resource: http://api.zap2it.com/tvlistings/webservices/whatson?stnlt=72755
  name: zaptva
  value_template: '{{ value_json.results.schedules[0].title }}'
- platform: rest
  resource: http://api.zap2it.com/tvlistings/webservices/whatson?stnlt=58688
  name: zapvtele
  value_template: '{{ value_json.results.schedules[0].title }}'
- platform: rest
  resource: http://api.zap2it.com/tvlistings/webservices/whatson?stnlt=56109
  name: zapserieplus
  value_template: '{{ value_json.results.schedules[0].title }}'
- platform: rest
  resource: http://api.zap2it.com/tvlistings/webservices/whatson?stnlt=59532
  name: zapcasa
  value_template: '{{ value_json.results.schedules[0].title }}'
- platform: rest
  resource: http://api.zap2it.com/tvlistings/webservices/whatson?stnlt=73142
  name: zaptvsport
  value_template: '{{ value_json.results.schedules[0].title }}' 

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

##################################################################################
##                               Amcrest camera    sensor                       ##
##################################################################################

#  - platform: amcrest
#    host: 192.168.67.114
#    username: admin
#    password: !secret cam3_pass
#    monitored_conditions:
#      - motion_detector

##################################################################################
##                               speed test sensor                              ##
##################################################################################

- platform: template
  sensors:
    router:
      value_template: '{% if is_state("binary_sensor.router", "on") %} {{ states.binary_sensor.router.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
      unit_of_measurement: 'ms'
    google:
      value_template: '{% if is_state("binary_sensor.google", "on") %} {{ states.binary_sensor.google.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
      unit_of_measurement: 'ms'

##################################################################################
##                               presence sensor                                ##
##################################################################################

- platform: template
  sensors:
    sebas_status:
      value_template: '{{ states.input_select.sebas_status_dropdown.state }}'
      friendly_name: 'Sebas'
    gen_status:
      value_template: '{{ states.input_select.gen_status_dropdown.state }}'
      friendly_name: 'Gen'
    livingroomchromecast:
      friendly_name: 'Living Room Chromecast'
      value_template: "{{ 'Online' if is_state('device_tracker.chromecast', 'home') else 'Offline' }}"
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - download
    - upload

- platform: command_line
  name: unoyulyvo
  command: "/usr/local/bin/python3 /config/test.py"
  scan_interval: 14400
  unit_of_measurement: 'hr'

- platform: template
  sensors:
    unoarrival:
      value_template: "{% set list = states.sensor.unoyulyvo.state.split('_') %} {{ list[0] }}"
      friendly_name: 'Arrival'
    unosarrival:
      value_template: "{% set list = states.sensor.unoyulyvo.state.split('_') %} {{ list[1] }}"
      friendly_name: 'Scheduled-Arrival'
    unodeparture:
      value_template: "{% set list = states.sensor.unoyulyvo.state.split('_') %} {{ list[2] }}"
      friendly_name: 'Departure'
    unosdeparture:
      value_template: "{% set list = states.sensor.unoyulyvo.state.split('_') %} {{ list[3] }}"
      friendly_name: 'Scheduled-Departure'
