##########  ############################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'People Greeting'

  trigger:
    - platform: state
      entity_id: group.sebas_trackers
      from: 'not_home'
      to: 'home'
      for: '00:02:00'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '09:00:00'
    - condition: time
      before: '21:30:00'
    - condition: state
      entity_id: input_boolean.speech_notifications
      state: 'on'

  action:
    service: tts.amazon_polly_say
    entity_id: media_player.speaker_1
    data_template:
      message: >
        <speak>
        <break time='.9s' />
        {%if now().strftime("%a") == 'Wed' or now().strftime("%a") == 'Sun'%}
          Today is {{now().strftime("%A")}} and {{now().strftime("%A")}} is garbage day.
        {%endif%}
        <break time='.9s' />
        {%if now().strftime("%a") == 'Wed'%}
          Both Recycling and regular Garbage goes out. Please take out all of the garbage cans tonight.
        {%endif%}
        <break time='.9s' />
        {%if now().strftime("%a") == 'Thu'%}
          Today is jacuzzi products, go put chlorine now.
        {%endif%}
        </speak>
      cache: true


- alias: Mark Sebas as just arrived
  trigger:
    - platform: state
      entity_id: device_tracker.devicename
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sebas_status_dropdown
        option: Just Arrived

- alias: Mark Sebas as home
  trigger:
    - platform: state
      entity_id: input_select.sebas_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.sebas_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  condition:
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sebas_status_dropdown
        option: Home

- alias: Mark Sebas as just left
  trigger:
    - platform: state
      entity_id: device_tracker.devicename
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sebas_status_dropdown
        option: Just Left

- alias: Mark Sebas as away
  trigger:
    - platform: state
      entity_id: input_select.sebas_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sebas_status_dropdown
        option: Away

- alias: Mark Sebas as just arrived
  trigger:
    - platform: state
      entity_id: device_tracker.devicename
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sebas_status_dropdown
        option: Just Arrived

- alias: Mark Gen as home
  trigger:
    - platform: state
      entity_id: input_select.gen_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.gen_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  condition:
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gen_status_dropdown
        option: Home

- alias: Mark Gen as just left
  trigger:
    - platform: state
      entity_id: device_tracker.iphonedegen
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gen_status_dropdown
        option: Just Left

- alias: Mark Gen as away
  trigger:
    - platform: state
      entity_id: input_select.gen_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gen_status_dropdown
        option: Away
- alias: "RDS1 from HASS"
  trigger:
    platform: state
    entity_id: input_select.test_tv_channels
    to: 'RDS1'
  action:
    service: script.turn_on
    entity_id: script.rds1
- alias: "RDS2 from HASS"
  trigger:
    platform: state
    entity_id: input_select.test_tv_channels
    to: 'RDS2'
  action:
    service: script.turn_on
    entity_id: script.rds2