- alias: "Update Available Notification"
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater

  condition:
    - condition: template
      value_template: "{{ states('updater.updater') != 'unknown' }}"

  action:

    - service: script.tweet_engine
      data:
        tweet: "New version of @Home_Assistant! Cannot wait for Sebastian to install it! - {{ states('updater.updater') }}"


    - service: persistent_notification.create
      data:
        title: "Update Available"
        message: "Home Assistant {{ states('updater.updater') }} is available. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
        notification_id: "update_available"
